blank_issues_enabled: false

contact_links:
  - name: ðŸ’¬ Support & Questions
    url: https://github.com/aj-phillips/IconSwapperGui/discussions
    about: Please ask general questions, usage help, or support requests here.
